# -*- coding: utf-8 -*-
"""ExpenseTracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pICaVTX-s9CyGgTQmXmSyUcf9ITGBIwv
"""

# Expense Tracker.
exp = {}
total = 0
print("-----------Welcome to Expense Tracker.---------\n")
while True:
  print("1 . Add Expense.")
  print("2 . View Expense.")
  print("3 . Total Expense.")
  print("4 . Maximum Expense.")
  print("5 . Minimum Expense.")
  print("6 . Exit.\n")
  choice = int(input("Enter Your Choice :- "))
  if choice == 1:
    n = int(input("Enter Number Of Expenses :- "))
    for i in range(n):
      ne = input(f"Enter Expense Name {i+1} :- ")
      es = int(input("Enter Expense :- "))
      exp[ne]=es
      print("Expense Added Successfully.")
      print("-----------------------------\n")
  elif choice == 2:
    print("Expense List :- ")
    print("-----------------------------\n")
    for key , value in exp.items():
      print(
          f"{key:<10}"
          f"{value:<30}"
      )
    print("------------------------------\n")
  elif choice == 3:
    for value in exp.values():
      total += int(value)
    print("Total Expense :- ",total)
    print("-----------------------------\n")
  elif choice == 4:
    max = 0
    for value in exp.values():
      if max < int(value):
        max = int(value)
    print("Maximum Expense :- ",max)
    print("-----------------------------\n")
  elif choice == 5:
    min = 0
    for value in exp.values():
      if min == 0:
        min = int(value)
      elif min > int(value):
        min = int(value)
    print("Minimum Expense :- ",min)
    print("-----------------------------\n")
  elif choice == 6:
    print("Thank You For Coming.")
    break;
  else:
    print("Enter a Valid Choice.")